### ISSUE TITLE
I am getting error when try tedium

### ISSUE THREAD

**Issue by USUS-ILETISIM** [bretcope/tedium#4]
Hi,
my node version is 4.2.3 and when I test I am getting the following error...

```
Error:
var pool = yield tedium.createConnectionPool(tediousOptions, poolOptions);
                 ^^^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

The code is as follows from your npm page.
Also I tried it from the test Try I Out page and got the same error.

What I am doing wrong...

Best Regards...

``` js
var tedium = require('tedium');

var tediousOptions = {
  userName: 'user',
  password: 'pass',
  server: 'localhost',
  options: {
    database: 'DatabaseName'
  }
};

// passing pool options is optional, it defaults to this: 
var poolOptions = {
  min: 0,        // minimum connections to hold alive 
  max: 20,       // maximum number of connections which can be opened 
  timeout: 30000 // minimum amount of time a connection must sit idle before closing 
};

var pool = yield tedium.createConnectionPool(tediousOptions, poolOptions);
```

**Comment by bretcope** [comment]
The `yield` keyword only works inside generators. 

``` js
function * myGenerator() {
  // setup code ...

  var pool = yield tedium.createConnectionPool(tediousOptions, poolOptions);

  // do something with the pool ...
}
```

If your codebase is not using generators, you won't want to use Tedium. Also keep in mind that I'm not really maintaining Tedium anymore (too busy with other things). There's no reason it shouldn't still work, just don't expect updates unless someone wants to become a maintainer.
